// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apibeat.proto

package apibeatlog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogRequestData struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequestData) Reset()         { *m = LogRequestData{} }
func (m *LogRequestData) String() string { return proto.CompactTextString(m) }
func (*LogRequestData) ProtoMessage()    {}
func (*LogRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9158aeced9769ef, []int{0}
}

func (m *LogRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequestData.Unmarshal(m, b)
}
func (m *LogRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequestData.Marshal(b, m, deterministic)
}
func (m *LogRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequestData.Merge(m, src)
}
func (m *LogRequestData) XXX_Size() int {
	return xxx_messageInfo_LogRequestData.Size(m)
}
func (m *LogRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequestData proto.InternalMessageInfo

func (m *LogRequestData) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *LogRequestData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *LogRequestData) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogRequestData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogRequestData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LogResponseData struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponseData) Reset()         { *m = LogResponseData{} }
func (m *LogResponseData) String() string { return proto.CompactTextString(m) }
func (*LogResponseData) ProtoMessage()    {}
func (*LogResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9158aeced9769ef, []int{1}
}

func (m *LogResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponseData.Unmarshal(m, b)
}
func (m *LogResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponseData.Marshal(b, m, deterministic)
}
func (m *LogResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponseData.Merge(m, src)
}
func (m *LogResponseData) XXX_Size() int {
	return xxx_messageInfo_LogResponseData.Size(m)
}
func (m *LogResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponseData proto.InternalMessageInfo

func (m *LogResponseData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LogResponseData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LogRequestData)(nil), "apibeatlog.LogRequestData")
	proto.RegisterType((*LogResponseData)(nil), "apibeatlog.LogResponseData")
}

func init() { proto.RegisterFile("apibeat.proto", fileDescriptor_b9158aeced9769ef) }

var fileDescriptor_b9158aeced9769ef = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4e, 0xc4, 0x30,
	0x0c, 0x87, 0x55, 0xae, 0x5c, 0x85, 0x25, 0xfe, 0xc8, 0x03, 0x8a, 0x8e, 0x05, 0xdd, 0xc4, 0xd4,
	0x01, 0x06, 0x66, 0x4e, 0x2c, 0x48, 0xc7, 0xd2, 0x37, 0x70, 0x5b, 0x13, 0x2a, 0xd1, 0x3a, 0xd4,
	0x29, 0x4f, 0xc0, 0x83, 0xa3, 0xa4, 0xa9, 0x2a, 0x74, 0xdb, 0xf7, 0xc5, 0x96, 0xfd, 0x73, 0xe0,
	0x92, 0x5c, 0x57, 0x33, 0xf9, 0xd2, 0x8d, 0xe2, 0x05, 0x21, 0xe9, 0x97, 0xd8, 0xfd, 0x6f, 0x06,
	0x57, 0x47, 0xb1, 0x15, 0x7f, 0x4f, 0xac, 0xfe, 0x95, 0x3c, 0xa1, 0x81, 0x42, 0x79, 0xfc, 0xe9,
	0x1a, 0x36, 0xd9, 0x7d, 0xf6, 0x70, 0x51, 0x2d, 0x8a, 0xb7, 0xb0, 0x55, 0x99, 0xc6, 0x86, 0xcd,
	0x59, 0x2c, 0x24, 0x43, 0x84, 0xfc, 0x53, 0xd4, 0x9b, 0x4d, 0x7c, 0x8d, 0x1c, 0xa6, 0xf4, 0xac,
	0x4a, 0x96, 0x4d, 0x3e, 0x4f, 0x49, 0x1a, 0xba, 0x5b, 0xf2, 0x64, 0xce, 0xe7, 0xee, 0xc0, 0xfb,
	0x67, 0xb8, 0x8e, 0x29, 0xd4, 0xc9, 0xa0, 0x1c, 0x63, 0x20, 0xe4, 0x8d, 0xb4, 0x4b, 0x86, 0xc8,
	0x78, 0x03, 0x9b, 0x5e, 0x6d, 0xda, 0x1e, 0xf0, 0xf1, 0x1d, 0x8a, 0x17, 0xd7, 0x1d, 0x98, 0x3c,
	0x1e, 0xa0, 0x38, 0x8a, 0x7d, 0x1b, 0x3e, 0x04, 0x77, 0xe5, 0x7a, 0x62, 0xf9, 0xff, 0xbc, 0xdd,
	0xdd, 0x49, 0x6d, 0x5d, 0x5a, 0x6f, 0xe3, 0x0f, 0x3d, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x1d, 0xff, 0xd8, 0x32, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiBeatClient is the client API for ApiBeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiBeatClient interface {
	LogInfo(ctx context.Context, in *LogRequestData, opts ...grpc.CallOption) (*LogResponseData, error)
}

type apiBeatClient struct {
	cc *grpc.ClientConn
}

func NewApiBeatClient(cc *grpc.ClientConn) ApiBeatClient {
	return &apiBeatClient{cc}
}

func (c *apiBeatClient) LogInfo(ctx context.Context, in *LogRequestData, opts ...grpc.CallOption) (*LogResponseData, error) {
	out := new(LogResponseData)
	err := c.cc.Invoke(ctx, "/apibeatlog.ApiBeat/LogInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiBeatServer is the server API for ApiBeat service.
type ApiBeatServer interface {
	LogInfo(context.Context, *LogRequestData) (*LogResponseData, error)
}

func RegisterApiBeatServer(s *grpc.Server, srv ApiBeatServer) {
	s.RegisterService(&_ApiBeat_serviceDesc, srv)
}

func _ApiBeat_LogInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiBeatServer).LogInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apibeatlog.ApiBeat/LogInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiBeatServer).LogInfo(ctx, req.(*LogRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiBeat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apibeatlog.ApiBeat",
	HandlerType: (*ApiBeatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogInfo",
			Handler:    _ApiBeat_LogInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apibeat.proto",
}
